# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(default='', max_length=13)),
                ('nome', models.CharField(default='', max_length=25)),
                ('telefone', models.CharField(default='', max_length=16)),
                ('email', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(default='', max_length=7)),
                ('categoria', models.CharField(default='Ônibus', max_length=1)),
                ('qtde_lugares', models.IntegerField(default=0)),
                ('autonomia', models.DecimalField(decimal_places=2, default='0.00', max_digits=4)),
                ('veic_pronto', models.BooleanField(default=True)),
                ('dono_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(default='', max_length=11)),
                ('nome', models.CharField(default='', max_length=20)),
                ('telefone', models.CharField(default='', max_length=13)),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=25)),
                ('origem', models.CharField(max_length=250)),
                ('destino', models.CharField(max_length=250)),
                ('data_saida', models.CharField(max_length=250)),
                ('data_chegada', models.CharField(max_length=250)),
                ('hora_saida', models.CharField(max_length=250)),
                ('hora_chegada', models.CharField(max_length=250)),
                ('qtde_assentos', models.CharField(max_length=50)),
                ('qtde_assentos_disp', models.CharField(max_length=50)),
            ],
        ),
    ]
