# Generated by Django 2.0 on 2018-01-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoursite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='dono_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passageiro',
            name='dono_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viagem',
            name='dono_id',
            field=models.IntegerField(default=0),
        ),
    ]
