# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtoursite', '0002_viagem_nome_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('categoria', models.CharField(max_length=1)),
                ('qtde_lugares', models.IntegerField()),
                ('autonomia', models.DecimalField(decimal_places=2, max_digits=3)),
                ('veic_pronto', models.BooleanField()),
                ('onibus_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtoursite.Viagem')),
            ],
        ),
    ]
