# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoursite', '0003_onibus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onibus',
            name='onibus_viagem',
        ),
        migrations.AlterField(
            model_name='onibus',
            name='autonomia',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4),
        ),
        migrations.AlterField(
            model_name='onibus',
            name='categoria',
            field=models.CharField(default='Ônibus', max_length=1),
        ),
        migrations.AlterField(
            model_name='onibus',
            name='placa',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='onibus',
            name='qtde_lugares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='onibus',
            name='veic_pronto',
            field=models.BooleanField(default=True),
        ),
    ]
