# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=250)),
                ('destino', models.CharField(max_length=250)),
                ('data_saida', models.CharField(max_length=250)),
                ('data_chegada', models.CharField(max_length=250)),
                ('hora_saida', models.CharField(max_length=250)),
                ('hora_chegada', models.CharField(max_length=250)),
                ('qtde_assentos', models.CharField(max_length=50)),
                ('qtde_assentos_disp', models.CharField(max_length=50)),
            ],
        ),
    ]
