# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoursite', '0004_remove_onibus_onibus_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onibus',
            name='autonomia',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
