# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoursite', '0006_auto_20171018_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passageiro',
            name='passagem_paga',
        ),
    ]
